title: "Alejandro Morillas Torres Data Analytics"
description: "Portfolio y blog de an√°lisis de datos."
theme: minima

url: "https://alejandromtdata.github.io/website_data/"
baseurl: "/website_data"

author:
  name: "Alejandro"
  email: "alejandromtdev@gmail.com"

github_username: alejandromtdev
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - about.md
  - tecnologies.md
  - projects.md
